"use client";

import { VaultCard, Vault } from "./VaultCard";
import { Category } from "./CategoryMenu";

const mockVaults: Vault[] = [
  {
    id: "SV-BASE-001",
    name: "SV-BASE-001",
    protocol: "AAVE V3",
    network: "Base Sepolia",
    asset: "USDT",
    apy: 4.67,
    tvl: "$5,000",
    riskLevel: "Low",
    category: "lending",
    volatility: 0.01,
    total24hVol: "$0",
    bestLeverage: "1.0x",
    bestFixedApy: 4.67,
    depeggingRisk: "Low",
    currentApy: 4.67,
    yieldStability: 0.01,
    lockupPeriod: "None",
    gasCost: "$0.15 USDC",
    capitalUtilization: 50,
    currentCapacity: "$5,000",
    maxCapacity: "$10,000",
    exploitHistory: "None",
    timeSinceLaunch: "0 days",
    smartContractRiskScore: 92,
    avatarColor: "bg-blue-600",
    // Deployed contract addresses on Base Sepolia
    tokenAddress: "0x0a215D8ba66387DCA84B284D18c3B4ec3de6E54a",
    adapterAddress: "0x6F0b25e2abca0b60109549b7823392e3312f505c",
    poolManagerAddress: "0x7Da1D65F8B249183667cdE74C5CBD46dD38AA829",
    hookAddress: "0x1d16EAde6bE2D9037f458D53d0B0fD216FC740C4",
    aavePoolAddress: "0x6Ae43d3271ff6888e7Fc43Fd7321a503ff738951",
  },
  {
    id: "SV-ETH-002",
    name: "SV-ETH-002",
    protocol: "Morpho Blue",
    network: "Ethereum",
    asset: "USDC",
    apy: 8.5,
    tvl: "$650M",
    riskLevel: "Medium",
    category: "lending",
    volatility: 0.02,
    total24hVol: "$28.5M",
    bestLeverage: "3.5x",
    bestFixedApy: 8.5,
    depeggingRisk: "Low",
    currentApy: 8.5,
    yieldStability: 0.02,
    lockupPeriod: "None",
    gasCost: "$2.50 USDC",
    capitalUtilization: 78,
    currentCapacity: "$650M",
    maxCapacity: "$1.0B",
    exploitHistory: "None",
    timeSinceLaunch: "14 months",
    smartContractRiskScore: 88,
    avatarColor: "bg-purple-600",
  },
  {
    id: "SV-ARB-003",
    name: "SV-ARB-003",
    protocol: "Compound V3",
    network: "Arbitrum",
    asset: "USDT",
    apy: 3.8,
    tvl: "$890M",
    riskLevel: "Low",
    category: "lending",
    volatility: 0.02,
    total24hVol: "$38.7M",
    bestLeverage: "1.0x",
    bestFixedApy: 3.8,
    depeggingRisk: "Low",
    currentApy: 3.8,
    yieldStability: 0.015,
    lockupPeriod: "None",
    gasCost: "$0.08 USDC",
    capitalUtilization: 65,
    currentCapacity: "$890M",
    maxCapacity: "$1.5B",
    exploitHistory: "None",
    timeSinceLaunch: "22 months",
    smartContractRiskScore: 95,
    avatarColor: "bg-green-600",
  },
  {
    id: "SV-POL-005",
    name: "SV-POL-005",
    protocol: "Curve 3Pool",
    network: "Polygon",
    asset: "USDC/USDT/DAI",
    apy: 3.2,
    tvl: "$1.8B",
    riskLevel: "Low",
    category: "lending",
    volatility: 0.02,
    total24hVol: "$125.8M",
    bestLeverage: "1.0x",
    bestFixedApy: 3.2,
    depeggingRisk: "Medium",
    currentApy: 3.2,
    yieldStability: 0.015,
    lockupPeriod: "None",
    gasCost: "$0.05 USDC",
    capitalUtilization: 72,
    currentCapacity: "$1.8B",
    maxCapacity: "$2.5B",
    exploitHistory: "None",
    timeSinceLaunch: "36 months",
    smartContractRiskScore: 93,
    avatarColor: "bg-indigo-600",
  },
  {
    id: "SV-ETH-006",
    name: "SV-ETH-006",
    protocol: "Spark Protocol",
    network: "Ethereum",
    asset: "DAI → sDAI",
    apy: 4.5,
    tvl: "$2.7B",
    riskLevel: "Low",
    category: "lending",
    volatility: 0.01,
    total24hVol: "$18.9M",
    bestLeverage: "1.0x",
    bestFixedApy: 4.5,
    depeggingRisk: "Low",
    currentApy: 4.5,
    yieldStability: 0.01,
    lockupPeriod: "None",
    gasCost: "$2.80 USDC",
    capitalUtilization: 68,
    currentCapacity: "$2.7B",
    maxCapacity: "$4.0B",
    exploitHistory: "None",
    timeSinceLaunch: "16 months",
    smartContractRiskScore: 91,
    avatarColor: "bg-orange-600",
  },
  {
    id: "SV-OPT-007",
    name: "SV-OPT-007",
    protocol: "Yearn Finance",
    network: "Optimism",
    asset: "USDC",
    apy: 6.1,
    tvl: "$315M",
    riskLevel: "Medium",
    category: "lending",
    volatility: 0.03,
    total24hVol: "$8.4M",
    bestLeverage: "1.5x",
    bestFixedApy: 6.1,
    depeggingRisk: "Low",
    currentApy: 6.1,
    yieldStability: 0.025,
    lockupPeriod: "None",
    gasCost: "$0.12 USDC",
    capitalUtilization: 81,
    currentCapacity: "$315M",
    maxCapacity: "$500M",
    exploitHistory: "None",
    timeSinceLaunch: "24 months",
    smartContractRiskScore: 87,
    avatarColor: "bg-cyan-600",
  },
  {
    id: "SV-ARB-008",
    name: "SV-ARB-008",
    protocol: "AAVE V3",
    network: "Arbitrum",
    asset: "DAI",
    apy: 4.2,
    tvl: "$820M",
    riskLevel: "Low",
    category: "lending",
    volatility: 0.02,
    total24hVol: "$31.2M",
    bestLeverage: "1.0x",
    bestFixedApy: 4.2,
    depeggingRisk: "Medium",
    currentApy: 4.2,
    yieldStability: 0.018,
    lockupPeriod: "None",
    gasCost: "$0.09 USDC",
    capitalUtilization: 76,
    currentCapacity: "$820M",
    maxCapacity: "$1.2B",
    exploitHistory: "None",
    timeSinceLaunch: "20 months",
    smartContractRiskScore: 94,
    avatarColor: "bg-rose-600",
  },
  {
    id: "SV-ETH-009",
    name: "SV-ETH-009",
    protocol: "Ether.fi Cash",
    network: "Ethereum",
    asset: "USDC/USDT",
    apy: 10.2,
    tvl: "$425M",
    riskLevel: "Medium",
    category: "lending",
    volatility: 0.05,
    total24hVol: "$12.7M",
    bestLeverage: "2.2x",
    bestFixedApy: 10.2,
    depeggingRisk: "Low",
    currentApy: 10.2,
    yieldStability: 0.045,
    lockupPeriod: "7 days",
    gasCost: "$3.20 USDC",
    capitalUtilization: 85,
    currentCapacity: "$425M",
    maxCapacity: "$600M",
    exploitHistory: "None",
    timeSinceLaunch: "8 months",
    smartContractRiskScore: 82,
    avatarColor: "bg-pink-600",
  },
  {
    id: "SV-BASE-010",
    name: "SV-BASE-010",
    protocol: "Morpho Blue",
    network: "Base",
    asset: "USDC",
    apy: 7.8,
    tvl: "$580M",
    riskLevel: "Medium",
    category: "lending",
    volatility: 0.02,
    total24hVol: "$24.6M",
    bestLeverage: "2.9x",
    bestFixedApy: 7.8,
    depeggingRisk: "Low",
    currentApy: 7.8,
    yieldStability: 0.022,
    lockupPeriod: "None",
    gasCost: "$0.18 USDC",
    capitalUtilization: 79,
    currentCapacity: "$580M",
    maxCapacity: "$850M",
    exploitHistory: "None",
    timeSinceLaunch: "12 months",
    smartContractRiskScore: 86,
    avatarColor: "bg-teal-600",
  },
  // Perpetuals
  {
    id: "SV-PERP-001",
    name: "SV-PERP-001",
    protocol: "GMX V2",
    network: "Arbitrum",
    asset: "GLP",
    apy: 12.5,
    tvl: "$420M",
    riskLevel: "Medium",
    category: "perpetuals",
    volatility: 0.08,
    total24hVol: "$85.2M",
    bestLeverage: "50x",
    bestFixedApy: 12.5,
    depeggingRisk: "Medium",
    currentApy: 12.5,
    yieldStability: 0.06,
    lockupPeriod: "15 mins",
    gasCost: "$0.25 USDC",
    capitalUtilization: 82,
    currentCapacity: "$420M",
    maxCapacity: "$600M",
    exploitHistory: "None",
    timeSinceLaunch: "24 months",
    smartContractRiskScore: 88,
    avatarColor: "bg-violet-600",
  },
  {
    id: "SV-PERP-002",
    name: "SV-PERP-002",
    protocol: "Synthetix Perps",
    network: "Optimism",
    asset: "sUSD",
    apy: 15.8,
    tvl: "$180M",
    riskLevel: "High",
    category: "perpetuals",
    volatility: 0.12,
    total24hVol: "$42.8M",
    bestLeverage: "25x",
    bestFixedApy: 15.8,
    depeggingRisk: "Medium",
    currentApy: 15.8,
    yieldStability: 0.09,
    lockupPeriod: "None",
    gasCost: "$0.18 USDC",
    capitalUtilization: 76,
    currentCapacity: "$180M",
    maxCapacity: "$300M",
    exploitHistory: "None",
    timeSinceLaunch: "18 months",
    smartContractRiskScore: 84,
    avatarColor: "bg-fuchsia-600",
  },
  {
    id: "SV-PERP-003",
    name: "SV-PERP-003",
    protocol: "dYdX V4",
    network: "dYdX Chain",
    asset: "USDC",
    apy: 18.2,
    tvl: "$650M",
    riskLevel: "Medium",
    category: "perpetuals",
    volatility: 0.1,
    total24hVol: "$125.5M",
    bestLeverage: "20x",
    bestFixedApy: 18.2,
    depeggingRisk: "Low",
    currentApy: 18.2,
    yieldStability: 0.08,
    lockupPeriod: "None",
    gasCost: "$0.02 USDC",
    capitalUtilization: 88,
    currentCapacity: "$650M",
    maxCapacity: "$900M",
    exploitHistory: "None",
    timeSinceLaunch: "10 months",
    smartContractRiskScore: 90,
    avatarColor: "bg-purple-700",
  },
  {
    id: "SV-PERP-004",
    name: "SV-PERP-004",
    protocol: "Gains Network",
    network: "Polygon",
    asset: "DAI",
    apy: 22.5,
    tvl: "$95M",
    riskLevel: "High",
    category: "perpetuals",
    volatility: 0.15,
    total24hVol: "$28.3M",
    bestLeverage: "150x",
    bestFixedApy: 22.5,
    depeggingRisk: "Medium",
    currentApy: 22.5,
    yieldStability: 0.12,
    lockupPeriod: "None",
    gasCost: "$0.08 USDC",
    capitalUtilization: 72,
    currentCapacity: "$95M",
    maxCapacity: "$150M",
    exploitHistory: "None",
    timeSinceLaunch: "30 months",
    smartContractRiskScore: 85,
    avatarColor: "bg-indigo-700",
  },
  // Real World Assets
  {
    id: "SV-RWA-001",
    name: "SV-RWA-001",
    protocol: "Ondo Finance",
    network: "Ethereum",
    asset: "USDY",
    apy: 5.2,
    tvl: "$280M",
    riskLevel: "Low",
    category: "rwa",
    volatility: 0.005,
    total24hVol: "$8.5M",
    bestLeverage: "1.0x",
    bestFixedApy: 5.2,
    depeggingRisk: "Low",
    currentApy: 5.2,
    yieldStability: 0.003,
    lockupPeriod: "24 hours",
    gasCost: "$3.50 USDC",
    capitalUtilization: 92,
    currentCapacity: "$280M",
    maxCapacity: "$500M",
    exploitHistory: "None",
    timeSinceLaunch: "14 months",
    smartContractRiskScore: 89,
    avatarColor: "bg-emerald-600",
  },
  {
    id: "SV-RWA-002",
    name: "SV-RWA-002",
    protocol: "Maple Finance",
    network: "Ethereum",
    asset: "USDC",
    apy: 8.8,
    tvl: "$450M",
    riskLevel: "Medium",
    category: "rwa",
    volatility: 0.01,
    total24hVol: "$12.2M",
    bestLeverage: "1.0x",
    bestFixedApy: 8.8,
    depeggingRisk: "Low",
    currentApy: 8.8,
    yieldStability: 0.008,
    lockupPeriod: "90 days",
    gasCost: "$4.20 USDC",
    capitalUtilization: 85,
    currentCapacity: "$450M",
    maxCapacity: "$750M",
    exploitHistory: "None",
    timeSinceLaunch: "32 months",
    smartContractRiskScore: 91,
    avatarColor: "bg-lime-600",
  },
  {
    id: "SV-RWA-003",
    name: "SV-RWA-003",
    protocol: "Centrifuge",
    network: "Ethereum",
    asset: "DAI",
    apy: 6.5,
    tvl: "$185M",
    riskLevel: "Medium",
    category: "rwa",
    volatility: 0.008,
    total24hVol: "$5.8M",
    bestLeverage: "1.0x",
    bestFixedApy: 6.5,
    depeggingRisk: "Medium",
    currentApy: 6.5,
    yieldStability: 0.006,
    lockupPeriod: "30 days",
    gasCost: "$2.90 USDC",
    capitalUtilization: 78,
    currentCapacity: "$185M",
    maxCapacity: "$300M",
    exploitHistory: "None",
    timeSinceLaunch: "40 months",
    smartContractRiskScore: 87,
    avatarColor: "bg-teal-700",
  },
  {
    id: "SV-RWA-004",
    name: "SV-RWA-004",
    protocol: "Backed Finance",
    network: "Ethereum",
    asset: "bIB01",
    apy: 4.8,
    tvl: "$120M",
    riskLevel: "Low",
    category: "rwa",
    volatility: 0.004,
    total24hVol: "$3.2M",
    bestLeverage: "1.0x",
    bestFixedApy: 4.8,
    depeggingRisk: "Low",
    currentApy: 4.8,
    yieldStability: 0.002,
    lockupPeriod: "7 days",
    gasCost: "$3.80 USDC",
    capitalUtilization: 88,
    currentCapacity: "$120M",
    maxCapacity: "$200M",
    exploitHistory: "None",
    timeSinceLaunch: "16 months",
    smartContractRiskScore: 92,
    avatarColor: "bg-cyan-700",
  },
];

interface VaultListProps {
  category?: Category;
}

export const VaultList = ({ category = "all" }: VaultListProps) => {
  const filteredVaults = category === "all"
    ? mockVaults
    : mockVaults.filter((vault) => vault.category === category);

  return (
    <div className="bg-card rounded-lg border border-border overflow-hidden">
      {filteredVaults.length > 0 ? (
        filteredVaults.map((vault) => (
          <VaultCard key={vault.id} vault={vault} />
        ))
      ) : (
        <div className="p-12 text-center text-muted">
          No vaults found in this category
        </div>
      )}
    </div>
  );
};
